apiVersion: apps/v1
kind: Deployment
metadata:
  name: zolang-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zolang
  template:
    metadata:
      labels:
        app: zolang
    spec:
      volumes:
        - name: aws-cli
          emptyDir: {}
      initContainers:
        - name: install-aws-cli
          image: kryoengineering/container-mgmt
          command:
            - /bin/sh
            - -c
            - |
              yum install -y unzip && \
              curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip" && \
              unzip awscliv2.zip && \
              ./aws/install --update && \
              mv /usr/local/bin/aws /aws-cli/
          volumeMounts:
            - name: aws-cli
              mountPath: /aws-cli
      containers:
        - name: zolang
          image: 058264295714.dkr.ecr.ap-northeast-2.amazonaws.com/zolang:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: aws-cli
              mountPath: /usr/local/bin
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_secret_access_key
