apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zolang-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - zolang.site
      secretName: zolang-tls
  rules:
    - host: zolang.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zolang-service
                port:
                  number: 80
