apiVersion: apps/v1
kind: Deployment
metadata:
  name: zolang-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zolang
  template:
    metadata:
      labels:
        app: zolang
    spec:
      containers:
        - name: zolang
          image: 058264295714.dkr.ecr.ap-northeast-2.amazonaws.com/zolang:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: aws_secret_access_key
            - name: DOCKER_HOST
              value: "tcp://docker-daemon-service:2376"
      volumes:
        - name: dind-storage
          emptyDir: {}
