apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zolang-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "configmaps", "secrets", "networkpolicies", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "services", "deployments", "configmaps", "secrets", "networkpolicies", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]
